### ISSUE TITLE
Can't save D weight

### ISSUE THREAD

**Issue by ctzsnooze** [betaflight/betaflight-tx-lua-scripts#139] opened 2018-06-14 11:27 UTC
I have the 1.02 Lua scripts on an X9D running 2.2.1

On the page Rates 2/2 I can set and save all parameters *except* D weight.  If I change it and press save, I get Saving.... and then it reverts to the original value.  All other parameters on that screen can be saved without problems.

I'd be grateful for advice on how this might be fixed.

**Comment by luismiguelsi** [comment] 2018-07-01 18:15
i'd be gratefull too, thank you.

**Comment by mikeller** [comment] 2018-07-01 20:19
I think this was fixed in #140. But it's not yet released, you'll have to run latest from https://ci.betaflight.tech/job/Betaflight%20Lua%20-%20X7,%20X9,%20X9D,%20X9D+,%20X10,%20X12/lastSuccessfulBuild/artifact/.

**Comment by luismiguelsi** [comment] 2018-07-02 17:19
oh... perfect! thank you!

**Comment by codecae** [comment] 2018-07-13 23:33
Duplicate of #146

**Closed by codecae** 2018-07-13 23:33 UTC
