### ISSUE TITLE
Tramp Raceband 7 not displayed correctly

### ISSUE THREAD

**Issue by mawax** [betaflight/betaflight-tx-lua-scripts#10] opened 2017-02-05 21:43 UTC
Set the band to R and the channel to 7 and save. After loading the band changes to F and the channel to 8.
It will work though, as R7 and F8 are both 5880MHz.

**Comment by raphaelcoeffic** [comment] 2017-02-07 16:36
Yeah, the issue is basically in BF itself. It will be fixed shortly, but unfortunately too late for 3.1.4. The point is that we need to keep the settings in EEPROM, so that we know what was meant when a channel is set that shares the frequency with another channel.

See betaflight/betaflight#2335 for details/progresses.

**Comment by raphaelcoeffic** [comment] 2017-02-07 22:28
@mawax in BF 3.1.5, we reversed the lookup order, so that now F8 will be shown as R7 (still same frequency).

**Closed** 2017-02-24 14:04 UTC
