### ISSUE TITLE
ui.lua 335 error "not enough memory"

### ISSUE THREAD

**Issue by h4rr21** [betaflight/betaflight-tx-lua-scripts#114] opened 2018-02-11 05:35 UTC
opents-x9d+
vers: 2.2.1 (cca71808)

scripts version v1.0.1

receiver: XSR-E
FC: Omnibus F7 v2 (BF 3.2.4)

- can enter to the bf scripts the first time -> no values taken from the FC, just pages templates are shown
- second time I want to load the scripts page in my taranis, this error appears

**Comment by mikeller** [comment] 2018-02-11 06:34
Duplicate of #97.

**Closed by mikeller** 2018-02-11 06:34 UTC
